import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validate } from '../src/index.ts';
import type { Schema } from '../src/types.ts';

interface Case {
    rule: string;
    value: unknown;
    data?: Record<string, unknown>;
    schema: Schema;
    laravel: boolean;
    id: string;
}

/**
 * Every verdict here came from running Laravel's own validator, not from what
 * anyone believed it does. The fixture is regenerated by the PHP suite.
 */
const cases: Case[] = JSON.parse(
    readFileSync(new URL('./fixtures/parity.json', import.meta.url), 'utf8'),
);

test('the fixture is present and substantial', () => {
    assert.ok(cases.length > 100, `expected a real grid, got ${cases.length} cases`);
});

const divergences: string[] = [];

for (const c of cases) {
    test(`matches Laravel: ${c.id}`, () => {
        const values = c.data ?? { field: c.value };
        const result = validate(values, c.schema);

        // A field the runner cannot decide is neither valid nor invalid, so it
        // is excluded from the comparison rather than counted as agreement.
        if (result.undetermined.includes('field')) {
            return;
        }

        if (result.valid !== c.laravel) {
            divergences.push(`${c.id}: laravel=${c.laravel} runner=${result.valid}`);
        }

        assert.equal(
            result.valid,
            c.laravel,
            `${c.id}: Laravel says ${c.laravel}, the runner says ${result.valid}`,
        );
    });
}
